name: Docker (frontend)

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: "Build:checkout"
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Odyssey346
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/odyssey346/nofile:latest
          context: "."
          push: true
          no-cache: true
